### ISSUE TITLE
Coordinate PNPM Catalogs + Renovate + Release Plan

### ISSUE THREAD

**Issue by gossi** [embroider-build/release-plan#172]
As `pnpm` introduced its [catalogs feature](https://pnpm.io/catalogs), it is amazing to centrally control and manage versions for your (mono)repo. As a naive approach, I started grouping deps for ember in an ember catalog:

```yaml
catalogs:
  ember:
    "@ember/optional-features": "^2.2.0" # build
    "@ember/string": "^4.0.1" # frontend
    "@ember/test-helpers": "^3.3.1" # test
    "@embroider/addon-dev": "^8.0.1" # build
    "@embroider/addon-shim": "^1.10.0" # ?? (libraries, frontend)
    "@embroider/test-setup": "^4.0.0" # test
    "@glimmer/component": "^2.0.0" # frontend, libraries
    "@glimmer/tracking": "^1.1.2" # frontend, libraries
    "@glint/core": "^1.5.2" # build
    "@glint/environment-ember-loose": "^1.5.2" # build
    "@glint/template": "^1.5.2" # build
    # Can't use for e-a-i right now: https://github.com/embroider-build/ember-auto-import/issues/648
    # "ember-auto-import": "^2.10.0"
    "ember-cli": "~6.3.1" # build
    "ember-cli-app-version": "^7.0.0" # build
    "ember-cli-babel": "^8.2.0" # build
    "ember-cli-dependency-checker": "^3.3.3" # test
    "ember-cli-htmlbars": "^6.3.0" # build
    "ember-cli-inject-live-reload": "^2.1.0" # build
    "ember-cli-sri": "^2.1.1" # build
    "ember-engines": "^0.12.0" # prod ?
    "ember-intl": "^7.1.6" # frontend, libraries (runtime, build)
    "ember-load-initializers": "^3.0.1" # frontend (runtime ?, build ?)
    "ember-qunit": "^9.0.2" # test
    "ember-resolver": "^13.1.0" # frontend (runtime ?, build ?)
    "ember-source": "~6.4.0" # frontend
    "ember-source-channel-url": "^3.0.0" # test
    "ember-truth-helpers": "^4.0.3" # frontend, libraries
    "ember-try": "^4.0.0" # test
    "qunit": "^2.24.1" # test
    "qunit-dom": "^3.4.0" # test
```

Now that actually is really nice. Then I started using renovate for automated dependency management. Renovate is applying labels (`enhancement` rsp `internal`) to allow versioning with [release-plan](https://github.com/embroider-build/release-plan). Release-plan uses these labels to drop a minor rsp patch release. The two work perfectly hand-in-hand. So here is the related part in the renovate config:

```json5
{
  "packageRules": [
    // labels for release-plan
    {
      "matchDepTypes": [
        "devDependencies",
        "overrides",
        "resolutions",
        "pnpm.overrides",
        "engines",
        "packageManager"
      ],
      "addLabels": [
        "internal"
      ]
    },
    {
      "matchDepTypes": [
        "dependencies",
        "peerDependencies",
        "optionalDependencies"
      ],
      "addLabels": [
        "enhancement"
      ]
    },
    {
      "matchUpdateTypes": [
        "lockFileMaintenance"
      ],
      "addLabels": [
        "internal"
      ]
    },
    {
      "matchUpdateTypes": [
        "major"
      ],
      "matchDepTypes": [
        "engines"
      ],
      "addLabels": [
        "breaking"
      ]
    },
    {
      "matchDatasources": [
        "github-tags",
        "github-runners",
        "node-version"
      ],
      "addLabels": [
        "internal"
      ]
    }
  ]
}
```

That is to stick to semantic versioning with release automation and dependency automation tools. And it is a very nice situation.

My rule here is: if the dependency affects the consumers drop a minor release, if it only affects developing on the repo, drop a patch release. That very much depends on the dependency type (`dependency` vs. `devDependency`) as renovate is able to provide the metadata to then apply the right tag.

Plot twist: With catalogs that sort of metadata is no longer available. But [renovate supports matching against catalogs](https://docs.renovatebot.com/modules/manager/npm/#additional-information) (hooray). That means the naive grouping of "ember" catalog needs to break up. Luckily around the same time [Anthony Fu was posting about catalogs](https://antfu.me/posts/categorize-deps) and provided more factors to keep in mind. His ideas blend pretty much with mine and I really like the idea he proposes to categorize deps (you see me having them tagged above). With that it would look like:

```yaml
catalogs:
  build:
    "@ember/optional-features": "^2.2.0" # build
    "@embroider/addon-dev": "^8.0.1" # build
    "@glint/core": "^1.5.2" # build
    "@glint/core": "^1.5.2" # build
    "@glint/environment-ember-loose": "^1.5.2" # build
    "@glint/template": "^1.5.2" # build
    "ember-cli": "~6.3.1" # build
    "ember-cli-app-version": "^7.0.0" # build
    "ember-cli-babel": "^8.2.0" # build
    "ember-cli-htmlbars": "^6.3.0" # build
    "ember-cli-inject-live-reload": "^2.1.0" # build
    "ember-cli-sri": "^2.1.1" # build
    "typescript": "5.6.3" # build
    "tsup": "8.4.0" # build
    "webpack": "^5.99.6" # build (runtime ?)
    "vite": "^6.2.4" # build

  lint:
    "eslint": "^9.26.0" # lint
    "prettier": "^3.5.3" # lint
    "stylelint": "^16.18.0" # lint

  test:
    "@ember/test-helpers": "^3.3.1" # test
    "@embroider/test-setup": "^4.0.0" # test
    "ember-cli-dependency-checker": "^3.3.3" # test
    "ember-qunit": "^9.0.2" # test
    "ember-source-channel-url": "^3.0.0" # test
    "ember-try": "^4.0.0" # test
    "qunit": "^2.24.1" # test
    "qunit-dom": "^3.4.0" # test

  frontend:
    "@ember/string": "^4.0.1" # frontend
    "@embroider/addon-shim": "^1.10.0" # ?? (libraries, frontend)
    "@glimmer/component": "^2.0.0" # frontend, libraries
    "@glimmer/tracking": "^1.1.2" # frontend, libraries
    "ember-engines": "^0.12.0" # prod ?
    "ember-intl": "^7.1.6" # frontend, libraries (runtime, build)
    "ember-load-initializers": "^3.0.1" # frontend (runtime ?, build ?)
    "ember-resolver": "^13.1.0" # frontend (runtime ?, build ?)
    "ember-source": "~6.4.0" # frontend
    "ember-truth-helpers": "^4.0.3" # frontend, libraries
```

that looks very clean to me, tbh. 

Notes:

- Ember is not 100% on board supporting catalogs ([ember-auto-import](https://github.com/embroider-build/ember-auto-import/issues/648) has an issue with that)
- Renovate can make a different grouping for dep upgrades, that's good.

Open Questions:

- For library packages: 
	- I was thinking whether the deps affect runtime code (enhancement) or not (patch)
	- Frontend catalog: It will affect the consumers of our library
		- This is the catalog where I have the most question marks as I do not understand every package in there
	- Will packages that we use for build also affect the runtime?
	- Would that mean to separate those catalogs (seems weird)?
	    - `frontend-build` ?
	    - `frontend-runtime` ?
	- Am I overthinking here?
	- It is possible to combine matchers for renovate (that gives good control):
	  ```json
      {
        "matchUpdateTypes": [
          "major"
        ],
        "matchDatasources": [
          "pnpm.catalogs.frontend"
        ],
        "matchPackageNames": [
          "@ember/*"
        ],
        "addLabels": [
          "breaking"
        ]
      }
	  ```
- Is there a "higher need" to make such a thing a bit more "formal" (RFC?) for ember people?
